# Generated by Django 4.1.2 on 2022-10-26 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionDepart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('middlename', models.CharField(blank=True, max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('mobile', models.IntegerField()),
                ('emergency_mobile', models.IntegerField()),
                ('present_address', models.CharField(max_length=255)),
                ('present_city', models.CharField(max_length=255)),
                ('present_state', models.CharField(max_length=255)),
                ('present_zip', models.IntegerField()),
                ('permanent_address', models.CharField(max_length=255)),
                ('permanent_city', models.CharField(max_length=255)),
                ('permanent_state', models.CharField(max_length=255)),
                ('permanent_zip', models.IntegerField()),
                ('account_type', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
