# Generated by Django 4.1.2 on 2022-11-11 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissiondepart',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admission', to=settings.AUTH_USER_MODEL),
        ),
    ]
