# Generated by Django 4.1.2 on 2022-10-28 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admission', '0004_alter_admissiondepart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissiondepart',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admission', to=settings.AUTH_USER_MODEL),
        ),
    ]
