# Generated by Django 4.1.2 on 2022-10-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0006_admissionsalalry_admissiondepart_package_lpa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissiondepart',
            name='emergency_mobile',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='admissiondepart',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
    ]
