# Generated by Django 4.1.2 on 2022-11-13 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financedepartment',
            name='salary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finance_salary', to='finance.financesalary'),
        ),
    ]
