# Generated by Django 4.1.2 on 2022-10-14 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authsystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='new_login',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
