# Generated by Django 4.1.2 on 2022-10-21 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authsystem', '0002_customuser_new_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
