# Generated by Django 4.1.2 on 2022-11-01 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course_duration',
            field=models.CharField(max_length=255),
        ),
    ]
