# Generated by Django 4.1.2 on 2022-11-03 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_courses_course_duration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Courses',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='StudentCourseFee',
        ),
    ]
