# Generated by Django 4.1.2 on 2022-11-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0004_delete_courses_delete_student_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('duration', models.IntegerField()),
                ('fee', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
